[package]
name = "steel-cli"
version = "0.2.0"
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "steel"
path = "src/main.rs"

[dependencies]
once_cell = "1.10.0"
# steel = { path = "./steel", features = ["jit"] }
# steel = { path = "./crates/steel", features = [] }
steel-core = { path = "./crates/steel-core", version = "0.2.0", features = ["web", "sqlite"] }
steel-derive = { path = "./crates/steel-derive", version = "0.2.0"}
steel-repl = { path = "./crates/steel-repl", version = "0.2.0" }
env_logger = "0.9"
log = "0.4.14"
clap = { version = "3.1.17", features = ["derive"] }
dlopen = "0.1"
dlopen_derive = "0.1.4"

# [[bin]]
# name = "main"

[dev-dependencies]
tungstenite = { version = "0.17.2", features = ["rustls-tls-native-roots"] }
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.2.2"
serde_json = "1.0.81"

[workspace]
members = [
    ".",
    "crates/*",
]

[profile.release]
# debug = true
lto = true